/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_druid_jni_JniWrapper */

#ifndef _Included_org_apache_druid_jni_JniWrapper
#define _Included_org_apache_druid_jni_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_druid_jni_JniWrapper
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_druid_jni_JniWrapper_hello
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_druid_jni_JniWrapper
 * Method:    memoryEquals
 * Signature: ([BLjava/nio/ByteBuffer;J[BLjava/nio/ByteBuffer;JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_druid_jni_JniWrapper_memoryEquals
  (JNIEnv *, jobject, jbyteArray, jobject, jlong, jbyteArray, jobject, jlong, jint);

/*
 * Class:     org_apache_druid_jni_JniWrapper
 * Method:    aggregateCount
 * Signature: (Ljava/nio/ByteBuffer;[BI[II)V
 */
JNIEXPORT void JNICALL Java_org_apache_druid_jni_JniWrapper_aggregateCount
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jintArray, jint);

/*
 * Class:     org_apache_druid_jni_JniWrapper
 * Method:    aggregateDoubleSum
 * Signature: ([JLjava/nio/ByteBuffer;[BI[I[II)V
 */
JNIEXPORT void JNICALL Java_org_apache_druid_jni_JniWrapper_aggregateDoubleSum
  (JNIEnv *, jobject, jdoubleArray, jobject, jbyteArray, jint, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
